name: vgs
description: ""
publish_to: "none"
version: 5.0.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0 #provavelmente pode atualizar tranquilo
  url_launcher: ^6.3.2 #provavelmente pode atualizar tranquilo
  path_provider: ^2.1.1
  font_awesome_flutter: ^10.9.1
  firebase_analytics: ^12.0.4
  google_mobile_ads: ^6.0.0
  share_plus: ^12.0.1

  # radio
  radio_player: ^2.2.1
  # flutter_radio_player: 2.0.3 #PÃ©ssimo componente... nunca mais vamos utilizar
  mini_music_visualizer: ^1.1.4 #provavelmente pode atualizar tranquilo

  #tv
  chewie: ^1.13.0 #provavelmente pode atualizar tranquilo
  video_player: ^2.10.1 #provavelmente pode atualizar tranquilo
  firebase_core: ^4.2.1

  # colocar o ads

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/texts/
